application: appcfg-upload-test
version: trunk
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin/

- url: /.*
  script: request.py
